"""initial schema

Hand-written, not autogenerated - JSONB, generated tsvector columns, CHECK constraints and
partial/expression indexes are exactly the things Postgres/SQLAlchemy autogenerate gets
wrong or misses (work pack §2.3). Every statement here is read against `db/models.py`
column by column before being committed. Must round-trip clean:
`alembic upgrade head && alembic downgrade base && alembic upgrade head` on an empty
database - that CI job is what makes this migration "done", not a green `alembic history`.

Revision ID: 0001
Revises:
Create Date: 2026-09-09

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")  # similarity() - Parva's linkage query

    # ---- reference -----------------------------------------------------
    op.create_table(
        "carriers",
        sa.Column("dot_id", sa.Integer, primary_key=True, autoincrement=False),
        sa.Column("iata_code", sa.String(4)),
        sa.Column("name", sa.String(200)),
    )

    op.create_table(
        "airports",
        sa.Column("airport_id", sa.Integer, primary_key=True, autoincrement=False),
        sa.Column("iata_code", sa.String(3)),
        sa.Column("city_name", sa.String(120)),
        sa.Column("state", sa.String(2)),
        sa.Column("wac", sa.Integer),
    )
    op.create_index("ix_airports_iata_code", "airports", ["iata_code"])

    op.create_table(
        "aircraft",
        sa.Column("tail_number", sa.String(10), primary_key=True),
        sa.Column("first_seen", sa.Date),
        sa.Column("last_seen", sa.Date),
    )

    # ---- users (needed before documents/dispositions FK to it) ---------
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("email", postgresql.CITEXT(), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.CheckConstraint("role IN ('analyst','manager','admin')", name="ck_users_role"),
    )

    # ---- hazard taxonomy (needed before report_hazards FK to it) -------
    op.create_table(
        "hazard_categories",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("code", sa.String(64), nullable=False, unique=True),
        sa.Column("label", sa.String(120), nullable=False),
        sa.Column("severity_weight", sa.Numeric(3, 2), nullable=False),
    )

    # ---- operational spine (BTS) ----------------------------------------
    op.create_table(
        "flights",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("flight_date", sa.Date, nullable=False),
        sa.Column("reporting_airline", sa.String(4), nullable=False),
        sa.Column("dot_id", sa.Integer, sa.ForeignKey("carriers.dot_id"), nullable=False),
        sa.Column("flight_number", sa.Integer, nullable=False),
        sa.Column("tail_number", sa.String(10), sa.ForeignKey("aircraft.tail_number")),
        sa.Column(
            "origin_airport_id",
            sa.Integer,
            sa.ForeignKey("airports.airport_id"),
            nullable=False,
        ),
        sa.Column(
            "dest_airport_id",
            sa.Integer,
            sa.ForeignKey("airports.airport_id"),
            nullable=False,
        ),
        sa.Column("crs_dep_time", sa.Time),
        sa.Column("dep_time", sa.Time),
        sa.Column("dep_delay_minutes", sa.Integer),
        sa.Column("crs_arr_time", sa.Time),
        sa.Column("arr_time", sa.Time),
        sa.Column("arr_delay_minutes", sa.Integer),
        sa.Column("cancelled", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("cancellation_code", sa.String(1)),
        sa.Column("diverted", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("carrier_delay", sa.Integer),
        sa.Column("weather_delay", sa.Integer),
        sa.Column("nas_delay", sa.Integer),
        sa.Column("security_delay", sa.Integer),
        sa.Column("late_aircraft_delay", sa.Integer),
        sa.Column("distance", sa.Integer),
        sa.UniqueConstraint(
            "flight_date", "reporting_airline", "flight_number", "origin_airport_id"
        ),
        sa.CheckConstraint(
            "cancellation_code IS NULL OR cancellation_code IN ('A','B','C','D')",
            name="ck_flights_cancellation_code",
        ),
    )
    # Linkage query: date range scan against origin airport (work pack §2.4).
    op.create_index("ix_flights_date_origin", "flights", ["flight_date", "origin_airport_id"])

    # ---- documents and reports -------------------------------------------
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("sha256", sa.String(64), nullable=False, unique=True),
        sa.Column("s3_bucket", sa.String(200), nullable=False),
        sa.Column("s3_key", sa.String(500), nullable=False),
        sa.Column("original_filename", sa.String(255)),
        sa.Column("byte_size", sa.BigInteger),
        sa.Column("page_count", sa.Integer),
        sa.Column("uploaded_by", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("status", sa.String(20), nullable=False, server_default="received"),
        sa.Column("attempts", sa.Integer, nullable=False, server_default="0"),
        sa.Column("error_text", sa.Text),
        sa.CheckConstraint(
            "status IN ('received','queued','parsing','parsed','failed')",
            name="ck_documents_status",
        ),
    )
    # Partial index: once the backlog drains, almost every row is 'parsed' - indexing only
    # the rows we still care about keeps this small and hot (work pack §2.4).
    op.create_index(
        "ix_documents_status_active",
        "documents",
        ["status"],
        postgresql_where=sa.text("status <> 'parsed'"),
    )

    op.create_table(
        "reports",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column(
            "document_id",
            sa.BigInteger,
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("acn", sa.String(16), nullable=False, unique=True),
        sa.Column("page_from", sa.Integer),
        sa.Column("page_to", sa.Integer),
        sa.Column("report_date", sa.Date),
        sa.Column("local_time_of_day", sa.String(20)),
        sa.Column("synopsis", sa.Text),
        sa.Column("narrative", sa.Text, nullable=False),
        sa.Column(
            "narrative_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(narrative, ''))", persisted=True),
        ),
        sa.Column(
            "coded",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("priority", sa.Integer),
        sa.Column("state", sa.String(20), nullable=False, server_default="new"),
        sa.Column("assigned_to", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("manager_flagged", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.CheckConstraint(
            "state IN ('new','triaged','escalated','closed')", name="ck_reports_state"
        ),
    )
    op.create_index("ix_reports_priority_keyset", "reports", ["priority", "report_date", "id"])
    op.create_index(
        "ix_reports_narrative_tsv", "reports", ["narrative_tsv"], postgresql_using="gin"
    )
    op.create_index(
        "ix_reports_coded",
        "reports",
        ["coded"],
        postgresql_using="gin",
        postgresql_ops={"coded": "jsonb_path_ops"},
    )

    op.create_table(
        "report_fields",
        sa.Column(
            "report_id",
            sa.BigInteger,
            sa.ForeignKey("reports.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("path", sa.String(200), primary_key=True),
        sa.Column("value", sa.String(2000), primary_key=True),
    )

    op.create_table(
        "report_hazards",
        sa.Column(
            "report_id",
            sa.BigInteger,
            sa.ForeignKey("reports.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "category_id",
            sa.Integer,
            sa.ForeignKey("hazard_categories.id"),
            primary_key=True,
        ),
        sa.Column("source", sa.String(10), primary_key=True),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=False),
        sa.CheckConstraint("source IN ('nasa','model')", name="ck_report_hazards_source"),
    )
    op.create_index("ix_report_hazards_category", "report_hazards", ["category_id", "report_id"])

    op.create_table(
        "report_flight_links",
        sa.Column(
            "report_id",
            sa.BigInteger,
            sa.ForeignKey("reports.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("flight_id", sa.BigInteger, sa.ForeignKey("flights.id"), primary_key=True),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=False),
        sa.Column("method", sa.String(60), nullable=False),
    )

    # ---- analyst workflow -------------------------------------------------
    op.create_table(
        "dispositions",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("report_id", sa.BigInteger, sa.ForeignKey("reports.id"), nullable=False),
        sa.Column("analyst_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("state", sa.String(20), nullable=False),
        sa.Column("priority", sa.Integer),
        sa.Column("note", sa.String(4000)),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "state IN ('new','triaged','escalated','closed')",
            name="ck_dispositions_state",
        ),
    )

    op.create_table(
        "ingest_events",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("document_id", sa.BigInteger, sa.ForeignKey("documents.id")),
        sa.Column("event", sa.String(60), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text())),
    )


def downgrade() -> None:
    op.drop_table("ingest_events")
    op.drop_table("dispositions")
    op.drop_table("report_flight_links")
    op.drop_index("ix_report_hazards_category", table_name="report_hazards")
    op.drop_table("report_hazards")
    op.drop_table("report_fields")
    op.drop_index("ix_reports_coded", table_name="reports")
    op.drop_index("ix_reports_narrative_tsv", table_name="reports")
    op.drop_index("ix_reports_priority_keyset", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_documents_status_active", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_flights_date_origin", table_name="flights")
    op.drop_table("flights")
    op.drop_table("hazard_categories")
    op.drop_table("users")
    op.drop_table("aircraft")
    op.drop_index("ix_airports_iata_code", table_name="airports")
    op.drop_table("airports")
    op.drop_table("carriers")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS citext")
